"use client";

import { Button } from "@theseosaas/ui/components/button";
import { IconTile } from "@theseosaas/ui/components/icon-tile";
import { Markdown } from "@theseosaas/ui/components/markdown";
import { FadeIn } from "@theseosaas/ui/components/motion";
import { cn } from "@theseosaas/ui/lib/utils";
import { AlertTriangle, Check, Copy, Download, Info, Search } from "lucide-react";
import Link from "next/link";
import * as React from "react";

import { useContentItem } from "@/hooks/use-content";
import type { ContentDetail } from "@/lib/api";

/**
 * One generated post — the design's `/blog/[slug]` screen.
 *
 * The point of the screen is stated in the design's own annotation: "markdown
 * only, copy and paste into their stack". So the two things it must do
 * perfectly are render the article beautifully and hand over the source
 * unaltered. Preview and Markdown are the same string; the toggle only changes
 * how it's displayed.
 *
 * Export beyond plain .md — MDX, Contentful, WordPress — is not built, and the
 * amber note says so rather than leaving the user to discover it.
 *
 * Responsive: the design is desktop-only. The toolbar wraps to two rows below
 * `md`, the prose column keeps the design's 720px measure but drops to 15.5px
 * body on phones, and tables inside the article scroll rather than crush.
 */
export function ContentDetailView({
  projectId,
  contentId,
}: {
  projectId: string;
  contentId: string;
}) {
  const flow = useContentItem(contentId);
  const [mode, setMode] = React.useState<"preview" | "markdown">("preview");
  const item = flow.item;

  if (flow.isLoading && !item) {
    return (
      <main className="flex flex-1 items-center justify-center px-4 py-16">
        <IconTile tone="ink" size="xl" className="animate-pulse">
          <Search />
        </IconTile>
        <span className="sr-only">Loading post</span>
      </main>
    );
  }

  if (flow.isError || !item) {
    return (
      <main className="flex flex-1 items-center justify-center px-4 py-16">
        <div className="w-full max-w-md space-y-4 text-center">
          <IconTile tone="critical" size="xl" className="mx-auto">
            <AlertTriangle />
          </IconTile>
          <h1 className="font-display text-ink-900 text-2xl font-semibold">
            We couldn&apos;t load this post
          </h1>
          <p className="text-ink-400 text-base leading-relaxed">
            {flow.errorMessage ?? "Please try again in a moment."}
          </p>
          <Button onClick={flow.refetch}>Try again</Button>
        </div>
      </main>
    );
  }

  return (
    <>
      <Toolbar
        item={item}
        projectId={projectId}
        mode={mode}
        onModeChange={setMode}
        onPublish={() => flow.setStatus(item.status === "PUBLISHED" ? "GENERATED" : "PUBLISHED")}
        isUpdatingStatus={flow.isUpdatingStatus}
      />

      {item.body ? (
        <>
          <FrameworkNote />

          <main className="flex justify-center px-4 py-10 sm:px-8 lg:px-12 lg:pt-12 lg:pb-15">
            <div className="w-full max-w-[720px] min-w-0">
              {mode === "preview" ? (
                <FadeIn>
                  {item.metaDescription ? (
                    <p className="mb-6 text-[14px] leading-[1.7] text-[#5B6472] italic sm:text-[15px]">
                      {item.metaDescription}
                    </p>
                  ) : null}

                  <Markdown>{item.body}</Markdown>

                  <hr className="my-[34px] border-0 border-t border-[#E2E6EC]" />

                  <p className="text-[14px] leading-[1.7] text-[#5B6472] sm:text-[15px]">
                    Generated by TheSEOSaaS from{" "}
                    <span className="rounded-[4px] bg-[#F1F3F7] px-[5px] py-px font-mono text-[13.5px]">
                      {item.keywords[0] ?? "your audit"}
                    </span>
                    {item.wordCount ? ` — ${item.wordCount.toLocaleString()} words.` : "."}
                  </p>
                </FadeIn>
              ) : (
                <pre className="overflow-x-auto rounded-xl border border-[#E2E6EC] bg-[#FAFAFB] p-4 font-mono text-[12.5px] leading-[1.7] whitespace-pre-wrap text-[#28303C] sm:p-6 sm:text-[13px]">
                  {item.body}
                </pre>
              )}
            </div>
          </main>
        </>
      ) : (
        <PendingBody item={item} projectId={projectId} />
      )}
    </>
  );
}

function Toolbar({
  item,
  projectId,
  mode,
  onModeChange,
  onPublish,
  isUpdatingStatus,
}: {
  item: ContentDetail;
  projectId: string;
  mode: "preview" | "markdown";
  onModeChange: (mode: "preview" | "markdown") => void;
  onPublish: () => void;
  isUpdatingStatus: boolean;
}) {
  return (
    <div className="flex flex-col gap-3 border-b border-[#EDEFF3] bg-[#FAFAFB] px-4 py-4 sm:px-6 md:flex-row md:items-center md:justify-between md:gap-6 lg:px-8">
      <div className="flex min-w-0 flex-wrap items-center gap-x-3 gap-y-1.5">
        <Link
          href={`/dashboard/${projectId}/content`}
          className="text-[13px] font-normal whitespace-nowrap text-[#6B7480]"
        >
          Content
        </Link>
        <span className="text-[13px] text-[#D3D8E0]">/</span>
        <span className="text-[13px] whitespace-nowrap text-[#6B7480]">AI blog posts</span>
        <span className="hidden text-[13px] text-[#D3D8E0] sm:inline">/</span>
        <span className="hidden min-w-0 truncate text-[13px] font-medium text-[#0B1220] sm:inline">
          {item.title}
        </span>
        <StatusPill item={item} />
      </div>

      {item.body ? (
        <div className="flex flex-wrap items-center gap-3 md:shrink-0">
          <div className="flex items-center gap-0.5 rounded-lg bg-[#F1F3F7] p-[3px]">
            {(["preview", "markdown"] as const).map((option) => (
              <button
                key={option}
                type="button"
                onClick={() => onModeChange(option)}
                className={cn(
                  "rounded-[6px] px-3 py-[5px] text-[12.5px] capitalize",
                  mode === option
                    ? "bg-white font-medium text-[#0B1220] shadow-[0_1px_2px_rgba(11,18,32,0.06)]"
                    : "text-[#6B7480]",
                )}
              >
                {option}
              </button>
            ))}
          </div>

          <DownloadButton item={item} />
          <CopyButton body={item.body} />

          <button
            type="button"
            onClick={onPublish}
            disabled={isUpdatingStatus}
            className="text-[12.5px] font-medium whitespace-nowrap text-[#6B7480] disabled:opacity-50"
          >
            {item.status === "PUBLISHED" ? "Mark unpublished" : "Mark published"}
          </button>
        </div>
      ) : null}
    </div>
  );
}

function StatusPill({ item }: { item: ContentDetail }) {
  const label =
    item.status === "GENERATING"
      ? "Writing"
      : item.status === "PUBLISHED"
        ? "Published"
        : item.status === "FAILED"
          ? "Failed"
          : item.status === "ARCHIVED"
            ? "Archived"
            : "Ready to publish";

  const colour = item.status === "FAILED" ? "#DC2626" : "#0B1220";

  return (
    <span className="inline-flex shrink-0 items-center gap-1.5 rounded-full border border-[#DDE1E7] bg-[#F1F3F7] px-2 py-0.5 text-[11px] font-semibold whitespace-nowrap text-[#0B1220]">
      <span
        className={cn("size-[5px] rounded-full", item.status === "GENERATING" && "animate-pulse")}
        style={{ background: colour }}
      />
      {label}
    </span>
  );
}

/** The design's amber strip. It is a promise about scope, so it stays. */
function FrameworkNote() {
  return (
    <div className="flex items-start gap-2.5 border-b border-[#F5E4CE] bg-[#FFFBF5] px-4 py-3 sm:items-center sm:px-6 lg:px-8">
      <Info className="mt-px size-3.5 shrink-0 text-[#B45309] sm:mt-0" />
      <span className="text-[12.5px] leading-[1.55] text-[#7C3D12]">
        Plain markdown only — headings, lists, tables, quotes and links. Your site&apos;s own
        styles take over once it&apos;s pasted in. Framework-specific export (MDX, Contentful,
        WordPress) is coming.
      </span>
    </div>
  );
}

function CopyButton({ body }: { body: string }) {
  const [copied, setCopied] = React.useState(false);

  React.useEffect(() => {
    if (!copied) return;
    const timer = setTimeout(() => setCopied(false), 2000);
    return () => clearTimeout(timer);
  }, [copied]);

  return (
    <button
      type="button"
      onClick={async () => {
        try {
          await navigator.clipboard.writeText(body);
          setCopied(true);
        } catch {
          // Clipboard access can be refused (insecure origin, permissions).
          // The Markdown tab is the fallback — the text is selectable there.
          setCopied(false);
        }
      }}
      className="inline-flex items-center gap-[7px] rounded-lg bg-[#0B1220] px-[15px] py-[9px] text-[12.5px] font-medium whitespace-nowrap text-white"
    >
      {copied ? <Check className="size-[13px]" /> : <Copy className="size-[13px]" />}
      {copied ? "Copied" : "Copy markdown"}
    </button>
  );
}

function DownloadButton({ item }: { item: ContentDetail }) {
  return (
    <button
      type="button"
      onClick={() => {
        // Built and revoked here rather than held in state: the blob is only
        // needed for the instant the click lasts.
        const blob = new Blob([item.body ?? ""], { type: "text/markdown;charset=utf-8" });
        const url = URL.createObjectURL(blob);
        const link = document.createElement("a");
        link.href = url;
        link.download = `${slugify(item.title)}.md`;
        link.click();
        URL.revokeObjectURL(url);
      }}
      className="inline-flex items-center gap-1.5 rounded-lg border border-[#DFE3EA] bg-white px-[13px] py-2 text-[12.5px] font-medium whitespace-nowrap text-[#3F4854]"
    >
      <Download className="size-[13px]" />
      Download .md
    </button>
  );
}

function PendingBody({ item, projectId }: { item: ContentDetail; projectId: string }) {
  const isFailed = item.status === "FAILED";

  return (
    <main className="flex flex-1 items-center justify-center px-4 py-16">
      <div className="w-full max-w-md space-y-4 text-center">
        <IconTile tone={isFailed ? "critical" : "ink"} size="xl" className={cn("mx-auto", !isFailed && "animate-pulse")}>
          {isFailed ? <AlertTriangle /> : <Search />}
        </IconTile>
        <h1 className="font-display text-ink-900 text-2xl font-semibold">
          {isFailed ? "This post couldn't be written" : "Writing your post"}
        </h1>
        <p className="text-ink-400 text-base leading-relaxed">
          {isFailed
            ? (item.lastError ??
              "Something went wrong during generation. Your monthly allowance wasn't charged.")
            : "This takes a minute or two. You don't need to stay on this page — it'll be in your library when it's done."}
        </p>
        <Button variant="outline" render={<Link href={`/dashboard/${projectId}/content`} />}>
          Back to content
        </Button>
      </div>
    </main>
  );
}

function slugify(title: string): string {
  return (
    title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "")
      .slice(0, 80) || "post"
  );
}
